### ISSUE TITLE
zmap.io links to https://github.com/zmap/zgrab which says that it's deprecated

### ISSUE THREAD

**Issue by xtaran** [zmap/website#12]
Under the term "ZGrab" https://zmap.io/ links to https://github.com/zmap/zgrab. But that repo says that it's deprecated and https://github.com/zmap/zgrab2 is the replacement.

The website probably should be updated to reflect that, too,

**Comment by xtaran** [comment]
Then again, zgrab2 doesn't build a `zgrab2` binary for me, just `pkg/linux_amd64/github.com/zmap/zgrab2.a`....

**Comment by zakird** [comment]
Looks like this was fixed a while back.
